name: build-and-push-to-dockerhub

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ingtk/firestore-emulator:latest
          build-args: |
            PORT=8812
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
